services:
  vdoninja-monitor:
    container_name: video_nyanya
    image: firefly27/video_nyanya:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - HTTP_PORT=8050          # порт веб-интерфейса настроек, можно поменять
      - START_CONFIRM_SEC=5
      - HEALTHCHECK_INTERVAL_SEC=5
      - NOTIFY_MIN_GAP_SEC=30
    volumes:
      - ./monitor.html:/app/html/monitor.html:ro
      - ./browser-profile:/app/browser-profile
      - ./config:/app/config    # settings.json с настройками из веб-интерфейса
      - ./logs:/app/logs
