services:
  vdoninja-monitor:
    image: firefly27/video_nyanya:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - HTTP_PORT=8050          # порт веб-интерфейса настроек, можно поменять
    volumes:
      - ./monitor.html:/app/html/monitor.html:ro
      - ./browser-profile:/app/browser-profile
      - ./config:/app/config    # settings.json с настройками из веб-интерфейса
      - ./logs:/app/logs
